### ISSUE TITLE
gif broken 🥺

### ISSUE THREAD

**Issue by VinnyOG** [kwhite20/kwhite20.github.io#2]
<img width="779" alt="Screen Shot 2021-04-23 at 11 57 39 AM" src="https://user-images.githubusercontent.com/5099087/115917548-47cb8000-a42b-11eb-9646-d36004239263.png">

**Comment by VinnyOG** [comment]
pls2fix https://www.reddit.com/r/Ooer/

**Comment by VinnyOG** [comment]
https://youtu.be/3Au01smLR5E

**Comment by VinnyOG** [comment]
Proposed solution in #3

**Comment by kwhite20** [comment]
I fixed it! Don't use Markup & HTML together
